In [95]:
import os
import pandas as pd
from shutil import copyfile
import numpy as np

df1=pd.read_excel("/home/uraninjo/Desktop/Çalışmalar/Mergen1-Teknofest/Murat/TestPipeline/Temizveribilgisi.xlsx")
df2=pd.read_excel("/home/uraninjo/Desktop/Çalışmalar/Mergen1-Teknofest/Murat/TestPipeline/veribilgisi.xlsx")
df1

,HASTANO,BIRADS KATEGORİSİ,MEME KOMPOZİSYONU,KADRAN BİLGİSİ (SAĞ),KADRAN BİLGİSİ (SOL)
0,822670054,NaN,MURAT,a,NaN
1,822670190,NaN,eeee,b,NaN
2,822670196,NaN,NaN,NaN,NaN
3,822670198,NaN,NaN,NaN,NaN
4,822670200,NaN,NaN,NaN,NaN
...,...,...,...,...,...
6756,845285700,NaN,NaN,NaN,NaN
6757,845285709,NaN,NaN,NaN,NaN
6758,845285900,NaN,NaN,NaN,NaN
6759,845285930,NaN,NaN,NaN,NaN
6760,845285963,NaN,NaN,NaN,NaN

In [96]:
import pandas as pd

# Boş satırları doldurun
for hno in df1["HASTANO"]:
    hastano2 = df2[df2["HASTANO"] == hno]
    hastano1 = df1[df1["HASTANO"] == hno]

    if pd.isna(hastano1["BIRADS KATEGORİSİ"].iloc[0]) and not pd.isna(hastano2["BIRADS KATEGORİSİ"].iloc[0]):
        hastano1.loc[hastano1["BIRADS KATEGORİSİ"].isna(), "BIRADS KATEGORİSİ"] = hastano2["BIRADS KATEGORİSİ"].iloc[0]

    if pd.isna(hastano1["MEME KOMPOZİSYONU"].iloc[0]) and not pd.isna(hastano2["MEME KOMPOZİSYONU"].iloc[0]):
        hastano1.loc[hastano1["MEME KOMPOZİSYONU"].isna(), "MEME KOMPOZİSYONU"] = hastano2["MEME KOMPOZİSYONU"].iloc[0]

    df1.loc[df1["HASTANO"] == hno] = hastano1

# Sonuçları "sonuc.xlsx" dosyasına yazdırın
df1

,HASTANO,BIRADS KATEGORİSİ,MEME KOMPOZİSYONU,KADRAN BİLGİSİ (SAĞ),KADRAN BİLGİSİ (SOL)
0,822670054,BI-RADS1-2,MURAT,a,NaN
1,822670190,BI-RADS1-2,eeee,b,NaN
2,822670196,BI-RADS0,C,NaN,NaN
3,822670198,BI-RADS1-2,C,NaN,NaN
4,822670200,BI-RADS1-2,C,NaN,NaN
...,...,...,...,...,...
6756,845285700,BI-RADS4-5,D,NaN,NaN
6757,845285709,BI-RADS4-5,D,NaN,NaN
6758,845285900,BI-RADS4-5,B,NaN,NaN
6759,845285930,BI-RADS4-5,B,NaN,NaN
6760,845285963,BI-RADS4-5,C,NaN,NaN

In [94]:
df1.to_excel("combined.xlsx", index=False)

,HASTANO,BIRADS KATEGORİSİ,MEME KOMPOZİSYONU,KADRAN BİLGİSİ (SAĞ),KADRAN BİLGİSİ (SOL),"Birads Skoru (EK BİLGİ OLARAK VERİLMİŞTİR, YARIŞMADA İSTENMEYECEKTİR)"
0,822670054,BI-RADS1-2,D,NaN,NaN,Kategori 1: Negatif (bir sorun yok)
1,822670190,BI-RADS1-2,C,NaN,NaN,Kategori 1: Negatif (bir sorun yok)
2,822670196,BI-RADS0,C,"[ ""ÜST DIŞ""]","[ ""MERKEZ""]",Kategori 0: Ek değerlendirme tetkiki yapılmalıdır
3,822670198,BI-RADS1-2,C,"[ ""MERKEZ""]","[ ""MERKEZ"", ""ÜST DIŞ""]",Kategori 2: İyi huylu bulgular
4,822670200,BI-RADS1-2,C,"[ ""MERKEZ""]","[ ""MERKEZ"", ""ÜST DIŞ""]",Kategori 2: İyi huylu bulgular
...,...,...,...,...,...,...
6756,845285700,BI-RADS4-5,D,NaN,"[ ""MERKEZ"", ""ÜST DIŞ""]",Kategori 4: Şüpheli bulgular - Biyopsi yapılma...
6757,845285709,BI-RADS4-5,D,NaN,"[ ""ÜST DIŞ""]",Kategori 4: Şüpheli bulgular - Biyopsi yapılma...
6758,845285900,BI-RADS4-5,B,"[ ""MERKEZ"", ""ALT İÇ""]",NaN,Kategori 5: Büyük olasılıkla kanser olabilir -...
6759,845285930,BI-RADS4-5,B,"[ ""ÜST DIŞ""]",NaN,Kategori 5: Büyük olasılıkla kanser olabilir -...
6760,845285963,BI-RADS4-5,C,"[ ""ÜST DIŞ""]",NaN,Kategori 4: Şüpheli bulgular - Biyopsi yapılma...